sudo: required
services:
  - docker

before_install:
  - docker build -t zaferuz/docker-deact -f Dockerfile.dev .
script:
  - docker run zaferuz/docker-deact npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "east-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-244147688258"
  bucket_path: "Docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
